version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: nest-app
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - HOST=0.0.0.0
    env_file:
      - ./.env
    depends_on:
      - db
      # - redis
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: unless-stopped
    shm_size: 128mb
    env_file:
      - ./.env
    volumes:
      # do not need now
      - postgres-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - ${DB_PORT}:${DB_PORT}

  adminer:
    image: adminer:latest
    container_name: db-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db
# TODO: when it is start be important
# redis:
#   image: redis:8.2.1-alpine
#   container_name: redis-cache
#   restart: unless-stopped
#   volumes:
#     - redis-data:/data
#   ports:
#     - 6379:6379

volumes:
  postgres-data:
# redis-data:
