version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: nest-app
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      # - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      - HOST=0.0.0.0
    env_file:
      - ./.env
    depends_on:
      - cockroachdb
      - migrator

  cockroachdb:
    image: cockroachdb/cockroach:v24.2.0
    container_name: cockroachdb
    restart: unless-stopped
    # command: start-single-node --insecure --listen-addr=127.0.0.1 --http-addr=127.0.0.1:8080
    command: start-single-node --insecure
    env_file:
      - ./.env
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    ports:
      - ${DB_PORT}:${DB_PORT} # SQL порт CockroachDB
      - "8080:8080"

  migrator:
    image: flyway/flyway:latest
    container_name: flyway-migrator
    env_file:
      - ./.env
    command: >
      -url=jdbc:postgresql://cockroachdb:${DB_PORT}/defaultdb?sslmode=disable
      -user=${DB_USER}
      -password=${DB_PASSWORD}
      -baselineOnMigrate=true
      -connectRetries=10
      -connectRetriesInterval=5
      migrate
    volumes:
      - ./database/migrations:/flyway/sql
    depends_on:
      - cockroachdb

  # - redis
  # TODO: when it is start be important
# redis:
#   image: redis:8.2.1-alpine
#   container_name: redis-cache
#   restart: unless-stopped
#   volumes:
#     - redis-data:/data
#   ports:
#     - 6379:6379

volumes:
  cockroach-data:
# volumes:
#   postgres-data:
# redis-data:
