version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: nest-app
    restart: unless-stopped
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
  db:
    image: mysql:latest
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  adminer:
    image: adminer:latest
    container_name: db-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - db

  redis:
    image: redis:8.2.1-alpine
    container_name: redis-cache
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

volumes:
  mysql-data:
  redis-data:
