export enum PermissionsEnum {
  PERSONNEL_ADD = 'personnel:add',
  PERSONNEL_ROLE = 'personnel:role',
  PERSONNEL_INFO = 'personnel:info',
  PERSONNEL_DELETE = 'personnel:delete',
  PERSONNEL_GET_ALL = 'personnel:get-all',
  PERMITS_GET_ALL = 'permits:get-all',
  PERMITS_INFO = 'permits:info',
  ROLE_OPERATIONS = 'roles:operations',
  ABOUT_GET = 'about:get',
  ABOUT_UPDATE = 'about:update',
  DRINK_ADD = 'drink:add',
  DRINK_UPDATE = 'drink:update',
  DRINK_DELETE = 'drink:delete',
  DISH_ADD = 'dish:add',
  DISH_UPDATE = 'dish:update',
  DISH_DELETE = 'dish:delete',
  CATEGORY_ADD = 'category:add',
  CATEGORY_UPDATE = 'category:update',
  CATEGORY_DELETE = 'category:delete',
  MENU_ADD = 'menu:add',
  MENU_UPDATE = 'menu:update',
  MENU_DELETE = 'menu:delete',
  MENU_ONBOARD = 'menu:onboard',
  MANAGER_INFO = 'manager:info',
  EMPLOYEE_ADD = 'employee:add',
  EMPLOYEE_INFO = 'employee:info',
  EMPLOYEE_DELETE = 'employee:delete',
  ORDER_READ = 'order:read',
  ORDER_UPDATE = 'order:update',
  // TODO:  next permits need to add to DB
  // ROLE_ADD = 'role:add',
  // ROLE_UPDATE = 'role:update',
  // ROLE_INFO = 'role:info',
  // ROLE_DELETE = 'role:delete'
}
